const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Particles,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Flash,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerTransparent,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Exps.MaxSpeed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Browser.Acts.Focus,
		C3.Plugins.Audio.Cnds.IsTagPlaying
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{isCanRun: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Timer: 0},
	{Spooner: 0},
	{Browser: 0},
	{Touch: 0},
	{MoveTo: 0},
	{Cam: 0},
	{Anchor: 0},
	{Level_TXT: 0},
	{DestroyOutsideLayout: 0},
	{Particles: 0},
	{Bullet: 0},
	{Rotate: 0},
	{Spoon: 0},
	{Poof: 0},
	{Fade: 0},
	{XP_TXT: 0},
	{Phone: 0},
	{Ground: 0},
	{Audio: 0},
	{Pin: 0},
	{Spooner_Shadow: 0},
	{BG2: 0},
	{Score_TXT: 0},
	{Sine: 0},
	{Menu_Spooner: 0},
	{TiledBackground: 0},
	{Flash: 0},
	{Play_BTN: 0},
	{Play_BTN2: 0},
	{Play_BTN3: 0},
	{Exit_BTN: 0},
	{Cursor: 0},
	{Telekinez: 0},
	{Upgrade_BTN: 0},
	{Upgrd: 0},
	{Upgrade_BTN2: 0},
	{Progress: 0},
	{CurProgress: 0},
	{Level: 0},
	{Score: 0}
];

self.InstanceType = {
	BG: class extends self.ISpriteInstance {},
	Spooner: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Cam: class extends self.ISpriteInstance {},
	Level_TXT: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	Spoon: class extends self.ISpriteInstance {},
	Poof: class extends self.ISpriteInstance {},
	XP_TXT: class extends self.ITextInstance {},
	Phone: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Spooner_Shadow: class extends self.ISpriteInstance {},
	BG2: class extends self.ISpriteInstance {},
	Score_TXT: class extends self.ITextInstance {},
	Menu_Spooner: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Play_BTN: class extends self.ITextInstance {},
	Play_BTN2: class extends self.ITextInstance {},
	Play_BTN3: class extends self.ITextInstance {},
	Exit_BTN: class extends self.ITextInstance {},
	Cursor: class extends self.ISpriteInstance {},
	Telekinez: class extends self.ISpriteInstance {},
	Upgrade_BTN: class extends self.ITextInstance {},
	Upgrd: class extends self.ISpriteInstance {},
	Upgrade_BTN2: class extends self.ITextInstance {}
}